### ISSUE TITLE
self not defined - refactor for server side rendering

### ISSUE THREAD

**Issue by bkniffler** [mikemintz/react-rethinkdb#1]
Hi, 
I'm getting "self not defined" on line 1194 in index.js of rethinkdb-websocket-client module, the line:

var method = self[methodName];

**Comment by mikemintz** [comment]
Hi @bkniffler,

What browser are you using? How are you building your javascript files for the browser (e.g. npm and webpack)?

**Comment by mikemintz** [comment]
Or are you running in node.js instead of browser? It looks like self is only available in the browser, so there's still some work to be done to get this to run in node.js

**Comment by bkniffler** [comment]
Hey, sorry for not giving loads of infos, it was just a quick, late try.

So, I build my app isomorphically, the components being rendered server-side using require('babel/register') and React.renderToString(). Like here for example: https://github.com/iam4x/isomorphic-flux-boilerplate

The issue appears within node, not the browser, so I guess you are right.

**Comment by bkniffler** [comment]
I guess this is the wrong place for this issue, I'll reopen this in the client library.

**Comment by mikemintz** [comment]
Implemented in https://github.com/mikemintz/react-rethinkdb/pull/2

This will be in 0.2.0

**Comment by mikemintz** [comment]
I wasn't able to easily integrate with flux in isomorphic-flux-boilerplate to register when the queries were complete. But if you can figure out how to set up the `alt.resolve` to wait for rethinkSession.onceDoneLoading then hopefully it should just work.

I did made an example isomorphic app without flux here that actually sort of works: https://github.com/mikemintz/react-rethinkdb/tree/master/examples/isomorphic

Thanks for letting me know about the incompatibility! Let me know if you have any other trouble getting it to work properly.
