### ISSUE TITLE
Support ES6 import syntax

### ISSUE THREAD

**Issue by gutenye** [mikemintz/react-rethinkdb#17]
```javascript
import Rethinkdb from "react-rethinkdb"
console.log(Rethinkdb)  //  -> undefined
```

Transpiled by babel, because of the [__esModule](https://github.com/esnext/es6-module-transpiler/issues/85) thing.

**Comment by mikemintz** [comment]
Thanks for reporting, I'll take a look through that thread.

In the meantime, can you see if `import * as Rethinkdb from "react-rethinkdb"` works for you?

**Comment by gutenye** [comment]
Great, that works :)

**Comment by mikemintz** [comment]
Right now I'm only using ES6 named exports. I think I should probably address this with [3.3 Having both named exports and a default export in a module](http://www.2ality.com/2014/09/es6-modules-final.html):

> As it turns out, you can actually have named exports and a default export at the same time.

**Comment by gutenye** [comment]
A quick way to fix it by adding `module.exports.default` in `rethinkdb-websocket-client/dist/index.js`

```
(function webpackUniversalModuleDefinition(root, factory) {                     
  if(typeof exports === 'object' && typeof module === 'object')  {               
    module.exports = factory();                 // used by require("rethinkdb-websocket-client")
    module.exports.default = factory();         // quick fix here, used by import RethinkdbWebsocketClient from "rethinkdb-websocket-client" which transpiled to require("rethinkdb-websocket-client").default if you defined __esModule
  }                                             
  ...
  Object.defineProperty(exports, '__esModule', {    // added by babel
    value: true
  });
  ...
```

But I'm not familiar with webpack, and have no idea how write it.

The other way around is don't use `export` in source code, use `modules.exports` instead.
