### ISSUE TITLE
Webpack npm install error

### ISSUE THREAD

**Issue by YonasBerhe** [mikemintz/react-rethinkdb#19]
Hello,

I'm having trouble compiling the frontend of the application. I get the following error each time I run "npm install".

![screen shot 2015-11-04 at 1 39 35 pm](https://cloud.githubusercontent.com/assets/8443899/10952830/9813e6d2-82f9-11e5-80b0-74faf613ecb8.png)

**Comment by mikemintz** [comment]
I suspect that's due to the latest version of babel requiring opt-in for react syntax. I'll update the tutorial to work with the newest version of babel.

**Comment by mikemintz** [comment]
@YonasBerhe This is now resolved in https://github.com/mikemintz/react-rethinkdb/commit/ec77b63b2c1127529126d836e9ef9cb1939ecb4e. Could you see if it works for you now?

If you don't want to start over, run `npm install babel-preset-react --save-dev` and create the `./.babelrc` file specified in https://github.com/mikemintz/react-rethinkdb/tree/master/examples/tutorial#add-babel-config
