### ISSUE TITLE
Flux / Redux integration

### ISSUE THREAD

**Issue by coffenbacher** [mikemintz/react-rethinkdb#22]
Is there a pattern to integrate this with Flux and/or Redux?

I like how the proxy server and the client are in separate packages, but there seems to be a lot of useful logic around subscriptions in this package that is tightly coupled to the mixin (at least, I can't figure out how to trivially separate it). 

Pulling this logic out and packaging it might be an easy solution to #8 - I don't need anything fancy like a mixin, for my use case at least. Just an interface to subscribe to changefeeds and pass the results to Redux.

**Comment by coffenbacher** [comment]
I realized I might be misinterpreting the division of labor here. Possibly I can just get away with using rethinkdb-websocket-client. I'll try that and report back...

**Comment by coffenbacher** [comment]
Actually, integrating with Redux was very straightforward working directly from https://github.com/mikemintz/rethinkdb-websocket-client instead! Awesome! 

I'm really surprised at the popularity difference between this package and the client - as far as I can tell this package doesn't work with React 0.14 yet (mixin issue) and that one is actually really straightforward and nice to use with Flux.

Anyways, no problem here in the end, I was just confused...

**Comment by mikemintz** [comment]
@coffenbacher, yes I think using rethinkdb-websocket-client with redux probably makes the most sense. The react-rethinkdb project is more intended to be a sideways data loading model where components directly specify their data queries as opposed to a flux model. It needs to track react component lifecycle so it can share results across components and unsubscribe from changefeeds when unmounting.

If you have any tips or run into any issues for integrating redux with rethinkdb-websocket-client, please post about them so others can benefit from what you've learned! I'd be interested in seeing what a simple component or project looks like using them together.

FWIW, react-rethinkdb should work fine with react 0.14, e.g. the [chat example app](https://github.com/mikemintz/react-rethinkdb/tree/master/examples/chat) runs with 0.14.2. Or did you mean to say that it doesn't work with ES6 class syntax (which is true until we implement https://github.com/mikemintz/react-rethinkdb/issues/8)?

**Comment by coffenbacher** [comment]
Great! This helps to understand the plan, thanks. 

The client works like a charm with Flux / Redux, I'll try to write up an example + tutorial at some point, because your work on the client is really excellent and is pretty cool when paired with Redux. Meteor-esque except for the latency compensation.

And yes, you're totally right about 0.14. All of our 0.14 projects use ES6, so I actually forgot you didn't need to use it.  :+1:
