### ISSUE TITLE
NPM missing dependency : webpack

### ISSUE THREAD

**Issue by Xrampino** [mikemintz/react-rethinkdb#26]
For the chat example, npm install fails because webpack is not installed

**Comment by mikemintz** [comment]
@Xrampino can you share the error that you're getting?

I'm also getting an error with the latest version, due to a behavior-changing eslint patch, which I will fix today. But I'm not getting any errors about webpack not being installed.

```
ERROR in ./client/app.jsx
Module build failed: YAMLException: Cannot read config file: /home/mike/code/react-rethinkdb/examples/chat/.eslintrc
Error: duplicated mapping key at line 49, column 32:
        "no-underscore-dangle": [0],
```

**Comment by mikemintz** [comment]
@Xrampino I'm going to close this, feel free to re-open and provide additional details if you're still getting an error in the latest version.
